dataset:
  train:
    - class: WetlabDataset
      mmap_dir: ./datasets/peptide_aigc_processed
      specify_index: ./datasets/peptide_aigc_processed/train.txt
      stype: raw
      neg_ratio: 1.0
    - names: ['train']
  valid:
    - class: WetlabDataset
      mmap_dir: ./datasets/peptide_aigc_processed
      specify_index: ./datasets/peptide_aigc_processed/valid.txt
      stype: raw
      test_mode: true
    - names: ['valid']

dataloader:
  train:
    shuffle: true
    num_workers: 4
    wrapper:
      class: DynamicBatchWrapper
      complexity: n*27 # KNN block graph with 3-edge sparsification
      ubound_per_batch: 250000  # batch size ~16
  valid:
    num_workers: 4
    wrapper:
      class: DynamicBatchWrapper
      complexity: n*27 # KNN block graph with 3-edge sparsification
      ubound_per_batch: 500000  # batch size ~32

trainer:
  class: AffinityTrainer
  config:
    proj_name: Uni-dG
    logger: tensorboard
    max_epoch: 200
    save_topk: 10
    val_freq: 1
    save_dir: ./ckpts/finetune_neg1
    patience: 10
    metric_min_better: true

    optimizer:
      class: AdamW
      lr: 1.0e-5

    scheduler:
      class: ReduceLROnPlateau
      factor: 0.6
      patience: 3
      mode: min
      frequency: val_epoch
      min_lr: 1.0e-6

model:
  class: AffinityModel
  model_type: GET
  hidden_size: 128
  n_channel: 1
  n_rbf: 32
  cutoff: 8.0
  n_head: 4
  radial_size: 64
  edge_size: 64
  k_neighbors: 9
  n_layers: 6
  loss_weights:
    regression: 0.4
    classification: 0.6

load_ckpt: ./checkpoints/model0.ckpt