dataset:
  test:
    - class: InterfaceDataset
      mmap_dir: ./datasets/abbench
    - class: InterfaceDataset
      mmap_dir: ./datasets/PDBbind/PL-refined
      specify_index: ./datasets/PDBbind/PL-refined/test.txt
    - class: InterfaceDataset
      mmap_dir: ./datasets/PPAB
      specify_index: ./datasets/PPAB/test.txt
    - class: InterfaceDataset # as positive sample
      mmap_dir: ./datasets/PDBbind/PL-refined
      specify_index: ./datasets/PDBbind/PL-refined/test.txt
    - class: DockedDataset
      mmap_dir: ./datasets/docked_PDBbind
      specify_index: ./datasets/docked_PDBbind/test.txt
      test_mode: true
    - class: InterfaceDataset # as positive sample
      mmap_dir: ./datasets/abbench
    - class: DockedDataset
      mmap_dir: ./datasets/docked_abbench
      pos_rmsd_th: 10.0
      test_mode: true
    - class: InterfaceDataset
      mmap_dir: ./datasets/PDBbind/NL
      specify_index: ./datasets/PDBbind/NL/test.txt
    - names: ['antibody', 'PL', 'PP', 'docked_PL', 'docked_PL', 'docked_antibody', 'docked_antibody', 'NL']

dataloader:
  test:
    num_workers: 4
    batch_size: 64